# Site settings
title: Oswego Pancake Breakfast
email: oswegokiwanis@gmail.com
url: https://oswegopancakes.com
description: "Oswego Kiwanis Pancake Breakfast Information Website"
keywords: "Oswego, Kiwanis, Pancake, Pancakes, Breakfast"
skills: "Come join the Kiwanis Club of Oswego & the Oswego Police Explorer Post 3525 on 02/29/2020 at Oswego High School from 8AM-12PM For Our Annual Pancake Breakfast! Enjoy an Amazing Breakfast & Support a Great Cause!"
meta_author: Kiwanis Oswego

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: 

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Oswego Kiwanis
  location: Oswego, IL
  social: Around the Web
  credits: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
 # - title: twitter
 #   url: http://twitter.com/jekyllrb
  - title: facebook
    url: https://www.facebook.com/oswegokiwanis/
  - title: external-link
    url: https://oswegokiwanis.portalbuzz.com/
 # - title: stack-overflow
 #   url: http://stackoverflow.com/questions/tagged/jekyll
 # - title: bitbucket
 #   url: http://bitbucket.org/jekyll
 # - title: github
 #   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 4th Annual Oswego Pancake Breakfast
  - line: Serving You Delicious Pancakes on 02/29/2020 8AM-12PM at
  - line: <a href="https://www.google.com/maps/place/Oswego+High+School/@41.6836911,-88.3436788,17z/data=!3m1!4b1!4m5!3m4!1s0x880eee13a09a2919:0x6625ea1b7a3d84c9!8m2!3d41.6836911!4d-88.3414901">Oswego High School, 4250 IL-71</a>
  - line: Oswego, IL 60543

# Credits content
credits: ''

# Build settings
markdown: kramdown
permalink: pretty
